### ISSUE TITLE
可以开源 WaWaJiWeb 的源码么？

### ISSUE THREAD

**Issue by ax003d** [zegodev/ZegoWaWaJi#3]
现在的代码目录只有 dist 目录。
我猜实际的源码应该是用 react 或者 vue.js 写的吧？
我现在想基于这个 H5 进行修改，直接修改 dist 里面的内容不太方便。
所以，可以开源 WaWaJiWeb 的源码么？

**Comment by zegodev** [comment]
1、WaWaJiWeb源码是原生写的，只是使用了webpack打包而已
2、而且打包后并没有做uglify混淆操作，只不过把源码注释给删掉了
3、后续会给一个有注释的版本
4、目前是1.0.0版本。请通过Tag来区分不同版本
5、jZego这个SDK是混淆的，开发者无需关注jZego这个SDK的实现逻辑
